#ifndef _LIGHT_DRAW_H
#define _LIGHT_DRAW_H

#include <light.h>

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

Light_Module_Declare(light_draw);

#define LIGHT_DRAW_BLACK      (uint16_t)0x0000
#define LIGHT_DRAW_WHITE      (uint16_t)0xFFFF

// glyphs[] is indexed directly by ASCII character code; unrendered code points are NULL.
// every non-NULL entry points to a (char_width+7)/8 * char_height byte buffer: 1 bit per
// pixel, MSB-first, row-major, 1 = black and 0 = white. this layout is shared with the C
// source/header pairs generated by font-crusher's 'crush render new' command, which emit
// glyph tables of exactly this shape wrapped in an extern const light_draw_font_t instance
#define LIGHT_DRAW_FONT_GLYPH_TABLE_SIZE 128

#define LIGHT_DRAW_POINT_1    1
#define LIGHT_DRAW_POINT_2    2
#define LIGHT_DRAW_POINT_3    3
#define LIGHT_DRAW_POINT_4    4
#define LIGHT_DRAW_POINT_5    5
#define LIGHT_DRAW_POINT_6    6
#define LIGHT_DRAW_POINT_7    7
#define LIGHT_DRAW_POINT_8    8

// rotation applies only to how logical (dim_x, dim_y) coordinates map onto the
// underlying physical buffer -- the buffer itself is always allocated at creation-time
// dimensions, matching whatever the display driver expects. LIGHT_DRAW_ROTATE_90/270 swap
// dim_x/dim_y so callers can keep drawing in whatever orientation is natural for their
// content (e.g. wide text) regardless of how the panel is physically mounted
#define LIGHT_DRAW_ROTATE_0     0
#define LIGHT_DRAW_ROTATE_90    1
#define LIGHT_DRAW_ROTATE_180   2
#define LIGHT_DRAW_ROTATE_270   3

// mirrors the logical coordinate space before rotation is applied (see
// light_draw_context_set_flip()). LIGHT_DRAW_FLIP_BOTH is equivalent to LIGHT_DRAW_ROTATE_180 applied on
// its own, but composes independently with whatever rotation is also set
#define LIGHT_DRAW_FLIP_NONE          0
#define LIGHT_DRAW_FLIP_HORIZONTAL    1
#define LIGHT_DRAW_FLIP_VERTICAL      2
#define LIGHT_DRAW_FLIP_BOTH          3

typedef struct light_draw_font {
    const uint8_t *const *glyphs;
    uint8_t char_width;
    uint8_t char_height;
} light_draw_font_t;

// 2x3 affine transform (the bottom row of the equivalent 3x3 homogeneous matrix is
// always [0 0 1], so it isn't stored):
//   phys_x = a*x + b*y + tx
//   phys_y = c*x + d*y + ty
// every logical-to-physical coordinate mapping (currently just rotation) is expressed
// as one of these, computed once when set rather than re-derived per pixel
typedef struct light_draw_transform {
    int32_t a, b, tx;
    int32_t c, d, ty;
} light_draw_transform_t;

typedef struct light_draw_context {
    const uint8_t *name;
    uint8_t *buffer;
    // NULL unless light_draw_context_enable_double_buffer() has been called -- the other half
    // of the front/back pair swapped by light_draw_context_swap_buffers()
    uint8_t *buffer_back;
    size_t buffer_length;
    // dim_x/dim_y are the LOGICAL dimensions callers draw against -- for
    // LIGHT_DRAW_ROTATE_90/270 these are swapped relative to phys_dim_x/phys_dim_y, which
    // describe the buffer's actual fixed layout (set once at creation and never
    // changed by rotation)
    uint16_t dim_x;
    uint16_t dim_y;
    uint16_t phys_dim_x;
    uint16_t phys_dim_y;
    uint8_t rotation;
    uint8_t flip;
    light_draw_transform_t transform;
    uint8_t px_bits;
    uint8_t px_bytes;
    uint8_t point_radius;
    uint16_t color_fg;
    uint16_t color_bg;
    //   the clip rectangle, in LOGICAL coordinates, inclusive. every primitive that goes
    // through the clipped pixel/span paths -- rects, circles, arcs, lines, text -- draws
    // nothing outside it, which is what lets a caller render a shape at its full geometry
    // and have it CUT OFF at an edge rather than redrawn smaller (a scrolled widget half
    // outside its container is the motivating case). defaults to the whole canvas, and is
    // reset to it whenever rotation or flip changes, since those redefine the space the
    // clip was expressed in. does NOT apply to light_draw_draw_clear() or the blits, which work on
    // the physical buffer wholesale
    uint16_t clip_x0, clip_y0;
    uint16_t clip_x1, clip_y1;
    const light_draw_font_t *font;
} light_draw_context_t;

typedef struct light_draw_point2d {
    uint16_t x;
    uint16_t y;
} light_draw_point2d;

light_draw_context_t *light_draw_context_create(const uint8_t *name, uint16_t width, uint16_t height, uint8_t px_bits);
void light_draw_context_set_font(light_draw_context_t *ctx, const light_draw_font_t *font);
// sets how logical (dim_x, dim_y) coordinates map onto the physical buffer allocated at
// creation time (see LIGHT_DRAW_ROTATE_* above). updates ctx->dim_x/dim_y in place; existing
// buffer content is not transformed, so this is meant to be called once during setup,
// before any drawing
void light_draw_context_set_rotation(light_draw_context_t *ctx, uint8_t rotation);
// mirrors the logical coordinate space (see LIGHT_DRAW_FLIP_* above), composing with whatever
// rotation is also set -- order doesn't matter, call this and light_draw_context_set_rotation()
// in either order. like rotation, existing buffer content is not transformed, so this
// is meant to be called once during setup, before any drawing
void light_draw_context_set_flip(light_draw_context_t *ctx, uint8_t flip);
//   restricts drawing to the given rectangle (logical coordinates, inclusive; clamped to the
// canvas) -- see clip_x0..clip_y1 on the context for exactly what honours it. set it, draw the
// shapes that must not escape, then light_draw_context_clear_clip() -- the clip is context state,
// and a caller that leaves it narrowed is quietly cropping everything drawn after it
void light_draw_context_set_clip(light_draw_context_t *ctx,
                uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1);
// puts the clip back to the whole canvas
void light_draw_context_clear_clip(light_draw_context_t *ctx);
// allocates a second buffer_length-sized buffer alongside ctx->buffer, for callers who
// want to render the next frame while a previous one is still being flushed to a display
// (see light_draw_context_swap_buffers()). optional -- most callers don't need this
void light_draw_context_enable_double_buffer(light_draw_context_t *ctx);
// flips ctx->buffer to the other allocated buffer (front/back swap). returns false
// (no-op) if double-buffering hasn't been enabled -- there's nothing to swap to. callers
// driving an async display update from this context should confirm nothing is still
// reading the target buffer first (see light_display_render_context_busy())
bool light_draw_context_swap_buffers(light_draw_context_t *ctx);
// maps a LOGICAL axis-aligned rect onto the PHYSICAL buffer's coordinate space, writing
// the result back as a normalised inclusive (min, max) pair. rotation and flip reorder
// which logical corner lands at which physical extreme, so the corners are transformed
// and then min/max'd rather than assumed to stay in order. every transform this supports
// maps axis-aligned rects to axis-aligned rects, so transforming two opposite corners
// recovers the exact physical bounds -- there's no need to visit all four. added for
// display drivers doing partial-region updates, which address the physical buffer while
// their callers naturally think in logical coordinates
void light_draw_transform_rect(const light_draw_context_t *ctx, light_draw_point2d p0, light_draw_point2d p1,
                         light_draw_point2d *out_min, light_draw_point2d *out_max);
// the inverse of the above, for a single point: maps a PHYSICAL buffer coordinate back into
// the LOGICAL space callers draw in. added for input rather than output -- a touch panel
// reports in the display's own physical frame, while everything layered above light_draw thinks
// in logical coordinates, and under rotation those are not the same point.
//
// exact, with no rounding: every rotation and flip matrix has entries in {-1, 0, 1} and
// determinant +/-1, and composing them preserves that, so the inverse is integer arithmetic
// (and 1/det == det). the result is clamped into dim_x/dim_y, since a touch panel whose
// coordinate range is slightly larger than the display's can otherwise map outside it
light_draw_point2d light_draw_untransform_point(const light_draw_context_t *ctx, light_draw_point2d phys);

// 1.0 in the Q15 fixed-point scale light_draw_blit_rotated() takes
#define LIGHT_DRAW_SCALE_ONE  32768

// samples `src` into ctx's own buffer, rotated by `angle_deg` about the buffer centre and
// scaled by `scale_q15` (LIGHT_DRAW_SCALE_ONE == 1:1). `src` must be a buffer of exactly ctx's
// geometry and pixel format -- typically the context's own back buffer, holding a previously
// rendered frame.
//
// works in PHYSICAL buffer space and ignores ctx->transform entirely: this rotates an image,
// it does not draw through the logical-to-physical mapping. that is what makes it usable for
// animating between two rotations, where the transform is precisely the thing in flux.
//
// INVERSE sampled -- for every destination pixel it maps back into the source and takes the
// nearest pixel. mapping source pixels forward instead would scatter them and leave unwritten
// gaps that widen with the scale factor. destination pixels whose source falls outside the
// buffer are left as they are, so clear first if that matters.
//
// SCALE IS NOT DECORATION: a w*h image rotated by 45 degrees needs a box of
// w*|sin| + h*|cos| on a side, so at 1:1 the corners fall outside a fixed buffer and are cut
// off part-way through a turn. pass light_draw_scale_inscribed() to keep the whole image visible.
//
// 16bpp only for now; a 1bpp path can follow if a mono panel ever needs one
void light_draw_blit_rotated(const light_draw_context_t *ctx, const uint8_t *src,
                       int16_t angle_deg, int32_t scale_q15);
// the largest scale at which a rotation by `angle_deg` still fits entirely inside a
// buffer of ctx's dimensions -- LIGHT_DRAW_SCALE_ONE at 0/180 degrees, smallest at 45
int32_t light_draw_scale_inscribed(const light_draw_context_t *ctx, int16_t angle_deg);

// copies `src` into ctx's own buffer displaced by (off_x, off_y). `src` must be a buffer of
// exactly ctx's geometry and pixel format, as for light_draw_blit_rotated().
//
// works in PHYSICAL buffer space and ignores ctx->transform, for the same reason
// light_draw_blit_rotated() does: this moves an image, it does not draw through the logical-to-
// physical mapping. A caller wanting to slide in a direction the VIEWER would name has to map
// that direction itself -- ctx->transform's `a` and `c` give the physical direction logical +x
// points in, which is exactly that mapping.
//
// destination pixels with no source -- the band uncovered by the displacement -- are left as
// they are, so whatever was drawn first shows through. That is what makes this usable for a
// transition: draw the incoming image, then slide the outgoing one off it.
//
// 16bpp only, matching light_draw_blit_rotated()
void light_draw_blit_offset(const light_draw_context_t *ctx, const uint8_t *src, int32_t off_x, int32_t off_y);

void light_draw_draw_circle(const light_draw_context_t *ctx, light_draw_point2d centre, uint16_t radius, bool fill);
// draws the part of a circle between two angles.
//
// ANGLE CONVENTION: 0 degrees points RIGHT (+x), and angles increase CLOCKWISE as seen on
// screen -- so 90 is straight DOWN. that follows from light_draw's y growing downward, and is
// stated explicitly because the opposite convention is equally defensible in the abstract
// and this is the first thing anyone gets wrong. angles outside 0..360 are wrapped, and
// end < start sweeps the long way round rather than drawing nothing.
//
// the step is derived from the radius so the arc never has gaps (see the implementation);
// the cost is that a pixel may be written twice where two steps land in the same cell, which
// is cheaper than de-duplicating and harmless for every drawing operation light_draw has
void light_draw_draw_arc(const light_draw_context_t *ctx, light_draw_point2d centre, uint16_t radius,
                   int16_t start_deg, int16_t end_deg);
// which corners light_draw_draw_rect_rounded_corners() rounds; the rest stay square
#define LIGHT_DRAW_CORNER_NONE         0x0
#define LIGHT_DRAW_CORNER_TOP_LEFT     0x1
#define LIGHT_DRAW_CORNER_TOP_RIGHT    0x2
#define LIGHT_DRAW_CORNER_BOTTOM_RIGHT 0x4
#define LIGHT_DRAW_CORNER_BOTTOM_LEFT  0x8
#define LIGHT_DRAW_CORNER_TOP          (LIGHT_DRAW_CORNER_TOP_LEFT | LIGHT_DRAW_CORNER_TOP_RIGHT)
#define LIGHT_DRAW_CORNER_BOTTOM       (LIGHT_DRAW_CORNER_BOTTOM_LEFT | LIGHT_DRAW_CORNER_BOTTOM_RIGHT)
#define LIGHT_DRAW_CORNER_LEFT         (LIGHT_DRAW_CORNER_TOP_LEFT | LIGHT_DRAW_CORNER_BOTTOM_LEFT)
#define LIGHT_DRAW_CORNER_RIGHT        (LIGHT_DRAW_CORNER_TOP_RIGHT | LIGHT_DRAW_CORNER_BOTTOM_RIGHT)
#define LIGHT_DRAW_CORNER_ALL          0xF

// a rectangle with rounded corners: the four straight edges shortened by the radius, plus a
// quarter arc at each inset corner. the radius is clamped to half the shorter side, so an
// over-large one degenerates into a stadium rather than drawing nonsense
void light_draw_draw_rect_rounded(const light_draw_context_t *ctx, light_draw_point2d p0, light_draw_point2d p1,
                            uint16_t radius, bool fill);
// the same, rounding only the corners named in `corners` (see LIGHT_DRAW_CORNER_* above) and
// leaving the others square.
//
// this exists for content sitting flush against the inside of a rounded container: a row at
// the bottom of a rounded panel wants its BOTTOM corners to follow the panel's curve while
// its top corners stay square against the row above it. rounding all four instead would
// pinch the row away from its neighbour for no reason
void light_draw_draw_rect_rounded_corners(const light_draw_context_t *ctx, light_draw_point2d p0, light_draw_point2d p1,
                            uint16_t radius, uint8_t corners, bool fill);
void light_draw_draw_point(const light_draw_context_t *img, light_draw_point2d p);
void light_draw_draw_line(const light_draw_context_t *ctx, light_draw_point2d p0, light_draw_point2d p1, bool solid);
void light_draw_draw_clear(const light_draw_context_t *ctx);
void light_draw_draw_text(const light_draw_context_t *ctx,
                    light_draw_point2d p, const uint8_t *text);
void light_draw_draw_rect(const light_draw_context_t *ctx,
                    light_draw_point2d p0, light_draw_point2d p1, bool fill);

uint8_t *light_draw_print_buffer(const light_draw_context_t *ctx);
void light_draw_debug_buffer_print_stdout(const light_draw_context_t *ctx);

#endif